name: AntiVPN
main: me.egg82.antivpn.BukkitBootstrap
version: 3.5.24
author: egg82
api-version: 1.14
description: Get the best; save money on overpriced plugins and block VPN users!
softdepend: [Plan, PlaceholderAPI]