name: AntiVPN
main: me.egg82.avpn.AntiVPN
version: 2.4.14
author: egg82
api-version: 1.13
description: Get the best; save money on overpriced plugins and block VPN users!
softdepends: [Plan]
commands:
  avpnreload:
    description: Reloads the plugin
    usage: /avpnreload
  avpntest:
    description: Test an IP through the various (enabled) services. Note that this forces a check so will use credits every time it's run.
    usage: /avpntest <ip>
  avpnscore:
    description: Scores a particular source based on a pre-made list of known good and bad IPs. Note that this forces a check so will use credits every time it's run.
    usage: /avpnscore <source>
  avpncheck:
    description: Check an IP using the default system. This will return exactly the same value as any other API call.
    usage: /avpncheck <ip>